# Example configuration file for evacuator
# This shows the actual YAML structure supported by the application
# Most users should use environment variables instead of config files
#

# Configuration precedence (highest to lowest priority):
# 1. Environment variables
# 2. Configuration file values
# 3. Default values


node_name: ""

provider:
  name: ""
  auto_detect: true
  poll_interval: "3s"
  request_timeout: "2s"

handler:
  kubernetes:
    enabled: false
    skip_daemon_sets: true
    delete_empty_dir_data: false
    kubeconfig: ""
    in_cluster: true

  telegram:
    enabled: false
    bot_token:
    chat_id:

log:
  level: "info"
  format: "json"

